/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'fluss.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./fluss.android-arm64.node')
          } else {
            nativeBinding = require('fluss-node-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'fluss.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./fluss.android-arm-eabi.node')
          } else {
            nativeBinding = require('fluss-node-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'fluss.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./fluss.win32-x64-msvc.node')
          } else {
            nativeBinding = require('fluss-node-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'fluss.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./fluss.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('fluss-node-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'fluss.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./fluss.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('fluss-node-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'fluss.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./fluss.darwin-universal.node')
      } else {
        nativeBinding = require('fluss-node-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'fluss.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./fluss.darwin-x64.node')
          } else {
            nativeBinding = require('fluss-node-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'fluss.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./fluss.darwin-arm64.node')
          } else {
            nativeBinding = require('fluss-node-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'fluss.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./fluss.freebsd-x64.node')
      } else {
        nativeBinding = require('fluss-node-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'fluss.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./fluss.linux-x64-musl.node')
            } else {
              nativeBinding = require('fluss-node-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'fluss.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./fluss.linux-x64-gnu.node')
            } else {
              nativeBinding = require('fluss-node-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'fluss.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./fluss.linux-arm64-musl.node')
            } else {
              nativeBinding = require('fluss-node-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'fluss.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./fluss.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('fluss-node-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'fluss.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./fluss.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('fluss-node-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'fluss.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./fluss.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('fluss-node-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'fluss.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./fluss.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('fluss-node-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'fluss.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./fluss.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('fluss-node-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'fluss.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./fluss.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('fluss-node-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { FlussAdmin, Config, FlussConnection, Lookuper, DataType, DataTypes, SchemaBuilder, Schema, TableDescriptorBuilder, TableDescriptor, TablePath, TableInfo, ChangeType, OffsetSpec, LakeSnapshot, DatabaseDescriptor, LogScanner, ScanRecords, FlussTable, TableAppend, AppendWriter, TableUpsert, TableLookup, TableScan, UpsertWriter, WriteResultHandle, EARLIEST_OFFSET } = nativeBinding

module.exports.FlussAdmin = FlussAdmin
module.exports.Config = Config
module.exports.FlussConnection = FlussConnection
module.exports.Lookuper = Lookuper
module.exports.DataType = DataType
module.exports.DataTypes = DataTypes
module.exports.SchemaBuilder = SchemaBuilder
module.exports.Schema = Schema
module.exports.TableDescriptorBuilder = TableDescriptorBuilder
module.exports.TableDescriptor = TableDescriptor
module.exports.TablePath = TablePath
module.exports.TableInfo = TableInfo
module.exports.ChangeType = ChangeType
module.exports.OffsetSpec = OffsetSpec
module.exports.LakeSnapshot = LakeSnapshot
module.exports.DatabaseDescriptor = DatabaseDescriptor
module.exports.LogScanner = LogScanner
module.exports.ScanRecords = ScanRecords
module.exports.FlussTable = FlussTable
module.exports.TableAppend = TableAppend
module.exports.AppendWriter = AppendWriter
module.exports.TableUpsert = TableUpsert
module.exports.TableLookup = TableLookup
module.exports.TableScan = TableScan
module.exports.UpsertWriter = UpsertWriter
module.exports.WriteResultHandle = WriteResultHandle
module.exports.EARLIEST_OFFSET = EARLIEST_OFFSET
